[package]
name = "benchmarks_jemalloc"
version = "0.1.0"
authors = ["Stephan HÃ¼gel <urschrei@gmail.com>"]

[dependencies]
unicode_test = { path = "../unicode_test" }
criterion = "0.2"
jemallocator = "0.1.8"

[[bench]]
name = "criterion_benchmark"
harness = false
